export const pokeFood = [
  {
    id: 1,
    type: "Misc",
    color: "#DB9D3C",
    name: "Mulligan Stew à la Cube",
  },
  {
    id: 2,
    type: "Red",
    color: "#FC6547",
    name: "Red Stew à la Cube",
  },
  {
    id: 3,
    type: "Blue",
    color: "#32F0FD",
    name: "Blue Soda à la Cube",
  },
  {
    id: 4,
    type: "Yellow",
    color: "#FEE93A",
    name: "Yellow Curry à la Cube",
  },
  {
    id: 5,
    type: "Gray",
    color: "#808080",
    name: "Gray Porridge à la Cube",
  },
  {
    id: 6,
    type: "Water",
    color: "#6A92ED",
    name: "Mouth-Watering Dip a la Cube",
  },
  {
    id: 7,
    type: "Normal",
    color: "#A8A77A",
    name: ["Plain Crepe a la Cube"],
  },
  {
    id: 8,
    type: "Poison",
    color: "#9F449E",
    name: "Sludge Soup a la Cube",
  },
  {
    id: 9,
    type: "Ground",
    color: "#DFBF6E",
    name: "Mud Pie a la Cube",
  },
  {
    id: 10,
    type: "Grass",
    color: "#7BC657",
    name: "Veggie Smoothie a la Cube",
  },
  {
    id: 11,
    type: "Bug",
    color: "#A8B731",
    name: "Honey Nectar a la Cube",
  },
  {
    id: 12,
    type: "Psychic",
    color: "#F65B89",
    name: "Brain Food a la Cube",
  },
  {
    id: 13,
    type: "Rock",
    color: "#B79F41",
    name: "Stone Soup a la Cube",
  },
  {
    id: 14,
    type: "Flying",
    color: "#A893ED",
    name: "Light-as-Air Casserole a la Cube",
  },
  {
    id: 15,
    type: "Fire",
    color: "#EE803B",
    name: "Hot Pot a la Cube",
  },
  {
    id: 16,
    type: "Electric",
    color: "#F7CF43",
    name: "Watt a Risotta a la Cube",
  },
  {
    id: 17,
    type: "Fighting",
    color: "#BE322E",
    name: "Get Swole Syrup a la Cube",
  },
  {
    id: 18,
    type: "Legend",
    color: "#F7CF43",
    name: "Ambrosia of Legends à la Cube",
  },
];
